// @ts-nocheck
// Independent presentation for the DSH Live Voice controls.
export const styles = `
.dlv-icon-button{display:inline-flex;align-items:center;justify-content:center;box-sizing:border-box;flex-shrink:0;cursor:pointer;background:transparent;color:var(--dsw-alias-label-secondary);padding:0;font:inherit}
.dlv-icon-button svg{display:block;width:20px;height:20px}
.dlv-mic{width:30px;height:30px;border:1px solid var(--dsw-alias-border-l1);border-radius:50%}
.dlv-composer-toggles{display:inline-flex;align-items:center;flex-shrink:0;gap:0;padding:2px;border:1px solid var(--dsw-alias-border-l1);border-radius:999px;background:transparent}
.dlv-composer-toggle{position:relative;width:34px;height:30px;border:0;border-radius:0;transition:background .15s ease,color .15s ease}.dlv-composer-toggles>.dlv-composer-toggle:first-child{border-radius:999px 0 0 999px}.dlv-composer-toggles>.dlv-composer-toggle:last-of-type{border-radius:0 999px 999px 0}.dlv-composer-toggles>.dlv-composer-toggle+.dlv-composer-toggle{border-left:1px solid var(--dsw-alias-border-l1)}
.dlv-composer-toggle[data-toggle-active=false]{color:var(--dsw-alias-label-secondary)}.dlv-composer-toggle[data-toggle-active=false] svg{opacity:.45}.dlv-composer-toggle[data-toggle-active=true]{background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary)}.dlv-composer-toggle[data-toggle-active=true] svg{opacity:1}.dlv-composer-toggle:hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}
@media(prefers-reduced-motion:reduce){.dlv-composer-toggle{transition:none}}
.dlv-mic:hover{color:var(--dsw-alias-label-primary);border-color:var(--dsw-alias-border-l2)}
.dlv-speaker{width:28px;height:28px;border:0;border-radius:28px;padding:5px;color:var(--dsw-alias-label-tertiary)}
.dlv-speaker:hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-secondary)}
.dlv-speaker[aria-pressed=true]{color:var(--dsw-alias-label-primary)}
.dlv-icon-button:disabled{opacity:.4;cursor:default}
.dlv-icon-button:focus-visible,.dlv-settings :is(input,select):focus-visible{outline:2px solid var(--dsw-alias-label-primary);outline-offset:3px}
.dlv-bar-wrap{width:100%;min-width:0}
.dlv-bar-stack{display:flex;flex-direction:column;gap:2px;width:100%;min-width:0}.dlv-bar-stack:empty{display:none}
.dlv-meeting-bars{width:100%}
.dlv-speech-bar{margin:0}.dlv-speech-pill{height:52px;min-height:52px;flex-wrap:nowrap!important}.dlv-caption{flex:1;min-width:0;overflow:hidden;white-space:nowrap;font-size:13px;line-height:1.4;color:var(--dsw-alias-label-primary)}.dlv-caption-stack{display:flex;flex-direction:column;gap:5px;flex:1;min-width:0}.dlv-caption-progress{visibility:hidden;height:2px;border-radius:2px;overflow:hidden;background:var(--dsw-alias-border-l1)}.dlv-caption-progress>span{display:block;height:100%;border-radius:inherit;background:var(--dsw-alias-label-primary);transition:width .1s linear}.dlv-speech-count{flex:none;font-size:11px;color:var(--dsw-alias-label-secondary)}
.dlv-caption-stage{position:relative;min-width:0;overflow:hidden;height:20px}.dlv-caption-scroll{display:block;width:100%;height:20px;overflow-x:auto;overflow-y:hidden;scrollbar-width:none;scroll-behavior:auto}.dlv-caption-scroll::-webkit-scrollbar{display:none}.dlv-caption-line{display:inline-block;white-space:pre}.dlv-caption-marker{position:absolute;left:0;top:0;height:20px;width:90px;border-radius:5px;pointer-events:none;background:linear-gradient(to right,transparent,color-mix(in srgb,var(--dsw-alias-label-primary) 15%,transparent) 35%,color-mix(in srgb,var(--dsw-alias-label-primary) 15%,transparent) 65%,transparent);box-shadow:inset 0 -2px 0 color-mix(in srgb,var(--dsw-alias-label-primary) 40%,transparent);will-change:transform}
.dlv-caption-progress[data-loading=true]{visibility:visible}.dlv-caption-progress[data-loading=true]>span{width:30%;animation:dlv-caption-loading 1.2s ease-in-out infinite;transition:none}@keyframes dlv-caption-loading{from{transform:translateX(-100%)}to{transform:translateX(350%)}}@media(prefers-reduced-motion:reduce){.dlv-caption-progress[data-loading=true]>span{animation:none;transform:translateX(115%)}}
.dlv-question-overlay{position:fixed;z-index:10000;bottom:8px;transform:translateX(-50%);max-width:calc(100vw - 32px);pointer-events:none}
.dlv-question-overlay .dlv-pill{pointer-events:auto}
.dlv-pill{display:flex;align-items:center;box-sizing:border-box;gap:10px;min-height:52px;border-radius:26px;background:var(--dsw-alias-bg-layer-1);border:1px solid var(--dsw-alias-border-l1);padding:0 14px;width:100%;max-width:720px;margin:0 auto;box-shadow:0 8px 24px rgba(0,0,0,.18)}
.dlv-pill-button{width:34px;height:34px;border-radius:50%;border:1px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-primary)}
.dlv-pill-button:hover{background:var(--dsw-alias-bg-layer-2)}
.dlv-live-toggle{width:34px;height:34px;padding:0 7px;gap:0;overflow:hidden;border:1px solid var(--dsw-alias-border-l2);border-radius:17px;color:var(--dsw-alias-label-primary);transition:width .16s ease,gap .16s ease}
.dlv-live-toggle svg{width:18px;height:18px;flex:none}
.dlv-toggle-state{max-width:0;opacity:0;overflow:hidden;white-space:nowrap;font-size:10px;font-weight:700;line-height:1;letter-spacing:.04em;text-align:left;transition:max-width .16s ease,opacity .12s ease}
.dlv-live-toggle:hover,.dlv-live-toggle:focus-visible,.dlv-live-toggle-expanded{width:78px;gap:5px;background:var(--dsw-alias-bg-layer-2)}
.dlv-live-toggle:hover .dlv-toggle-state,.dlv-live-toggle:focus-visible .dlv-toggle-state,.dlv-live-toggle-expanded .dlv-toggle-state{max-width:38px;opacity:1}
.dlv-live-toggle[data-toggle-active=false],.dlv-live-toggle[aria-checked=false],.dlv-live-toggle[data-mode=manual],.dlv-mic-state[data-muted=true]{color:var(--dsw-alias-label-tertiary);border-color:var(--dsw-alias-border-l1);opacity:.55}
.dlv-mic-state:hover,.dlv-mic-state:focus-visible{width:102px}.dlv-mic-state:hover .dlv-toggle-state,.dlv-mic-state:focus-visible .dlv-toggle-state{max-width:64px}
.dlv-live-toggle[data-toggle-active=true],.dlv-live-toggle[aria-checked=true]{background:var(--dsw-alias-bg-layer-2)}
.dlv-timestamp-toggle:hover,.dlv-timestamp-toggle:focus-visible{width:124px}.dlv-timestamp-toggle:hover .dlv-toggle-state,.dlv-timestamp-toggle:focus-visible .dlv-toggle-state{max-width:86px}
.dlv-wave{display:block;flex:1 1 180px;min-width:30px;width:0;height:40px;color:var(--dsw-alias-label-primary)}
.dlv-status{flex:1 1 120px;min-width:0;font-size:13px;line-height:1.4;color:var(--dsw-alias-label-secondary)}
.dlv-error{color:var(--dsw-alias-state-error-primary);overflow-wrap:anywhere;font-size:13px;max-width:720px;margin:8px auto}
.dlv-settings{box-sizing:border-box;padding:18px;width:100%;display:grid;gap:16px;max-width:640px;color:var(--dsw-alias-label-primary)}
.dlv-settings h3,.dlv-settings p{margin:0}
.dlv-settings-heading{display:flex;align-items:center;gap:8px;min-width:0;flex-wrap:wrap}
.dlv-plugin-update{display:inline-flex;flex-wrap:wrap;gap:6px;max-width:100%}.dlv-plugin-update-panel{display:flex;flex-wrap:wrap;align-items:center;gap:8px;width:100%;padding:10px;border:1px solid var(--dsw-alias-border-l1);border-radius:8px;font-size:12px;overflow-wrap:anywhere}.dlv-plugin-update button{cursor:pointer;font:inherit}.dlv-plugin-update button:disabled{opacity:.6;cursor:default}.dlv-plugin-update button:focus-visible{outline:2px solid var(--dsw-alias-label-primary);outline-offset:3px}.dlv-settings-heading h3{white-space:nowrap}.dlv-heading-divider{height:1px;min-width:12px;flex:1;background:var(--dsw-alias-border-l1)}.dlv-settings-heading .dlv-star-badge{flex:none}
.dlv-version-badges{display:flex;flex:none;gap:5px;align-items:center}.dlv-shields-badge{display:inline-flex;align-items:center;justify-content:center;box-sizing:border-box;height:20px;gap:4px;padding:3px 5px;border:1px solid var(--dsw-alias-border-l1);border-radius:5px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-secondary);font-size:10px;font-weight:650;line-height:12px;text-decoration:none}.dlv-shields-badge img{display:block;width:12px;height:12px;max-width:100%}.dlv-shields-badge:focus-visible{border-radius:4px;outline:2px solid var(--dsw-alias-label-primary);outline-offset:3px}.dlv-version-badge{display:inline-flex;align-items:center;min-height:24px;box-sizing:border-box;padding:3px 8px;border:1px solid var(--dsw-alias-border-l1);border-radius:999px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-secondary);font-size:11px;font-weight:650;line-height:16px;text-decoration:none}.dlv-version-badges a.dlv-version-badge:hover{border-color:var(--dsw-alias-border-l2);color:var(--dsw-alias-label-primary)}.dlv-star-badge{padding:4px 10px;color:var(--dsw-alias-label-primary)}.dlv-update-icon{margin-right:4px;font-size:14px;line-height:1}.dlv-star-icon{margin-right:4px;color:#f59e0b;font-size:14px;line-height:1;text-shadow:0 0 8px rgba(245,158,11,.28)}.dlv-version-badges a.dlv-star-badge:hover{border-color:#f59e0b;background:rgba(245,158,11,.08)}.dlv-update-badge{border-color:var(--dsw-alias-state-business-primary);color:var(--dsw-alias-state-business-primary)}
.dlv-settings-tabs{border-bottom:.5px solid var(--dsw-alias-border-l2);display:flex;align-items:flex-end;gap:22px;overflow-x:auto}.dlv-settings-tab{position:relative;display:inline-flex;align-items:center;gap:6px;flex:none;padding:7px 1px 9px;border:0;background:transparent;color:var(--dsw-alias-label-tertiary);font:inherit;font-size:16px;font-weight:600;line-height:22px;cursor:pointer}.dlv-settings-tab-icon{width:17px;height:17px;flex:none}.dlv-settings-tab:hover,.dlv-settings-tab[data-active=true]{color:var(--dsw-alias-label-primary)}.dlv-settings-tab[data-active=true]:after,.dlv-settings-tab:focus-visible:after{content:"";position:absolute;right:0;bottom:-1px;left:0;height:2px;border-radius:2px 2px 0 0;background:var(--dsw-alias-label-primary)}.dlv-settings-tab:focus-visible{border-radius:2px;outline:2px solid var(--dsw-alias-state-business-primary);outline-offset:2px;color:var(--dsw-alias-label-primary)}.dlv-settings-panel{min-width:0;padding-top:2px}.dlv-settings-panel[hidden]{display:none}.dlv-settings-group{margin:0;border:1px solid var(--dsw-alias-border-l1);border-radius:10px;min-width:0;display:grid;gap:14px;padding:16px}.dlv-settings-group legend{padding:0 6px;font-weight:600;color:var(--dsw-alias-label-primary)}.dlv-settings-card-body{display:grid;gap:18px;padding:8px 0 12px}.dlv-settings-subcard{min-width:0;margin:8px 0 0}.dlv-settings-subcard>summary{cursor:pointer;list-style:none;display:flex;align-items:center;gap:9px;padding:10px 12px;border-bottom:1px solid var(--dsw-alias-border-l1);border-radius:6px 6px 0 0;background:color-mix(in srgb,var(--dsw-alias-bg-layer-2) 38%,transparent);color:var(--dsw-alias-label-secondary);font-size:14px;font-weight:500;line-height:20px}.dlv-settings-subcard>summary::-webkit-details-marker{display:none}.dlv-settings-subcard>summary:focus-visible{outline:2px solid var(--dsw-alias-label-primary);outline-offset:3px}.dlv-settings-subcard-icon{width:16px;height:16px;flex:none}.dlv-settings-subcard-chevron{width:16px;height:16px;margin-left:auto;flex:none;transition:transform .15s}.dlv-settings-subcard[open]>summary .dlv-settings-subcard-chevron{transform:rotate(180deg)}.dlv-settings-subcard-body{display:grid;gap:16px;padding:18px 0 6px}
.dlv-settings label{display:grid;gap:6px;font-size:14px}.dlv-settings label.dlv-check{display:flex;align-items:center;gap:8px}.dlv-settings label.dlv-check input{width:auto}
.dlv-settings :is(input,select,textarea){box-sizing:border-box;width:100%;padding:8px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-layer-1);color:inherit;font:inherit}
.dlv-settings small,.dlv-settings p{font-size:13px;color:var(--dsw-alias-label-secondary);line-height:1.5}.dlv-settings .dlv-setting-description{line-height:1.65;margin:3px 0 5px}.dlv-settings .dlv-conversation-fields{display:grid;gap:20px;padding:4px 0}
.dlv-preset-group{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.dlv-settings label.dlv-preset{display:flex;align-items:flex-start;gap:8px;padding:10px;border:1px solid var(--dsw-alias-border-l1);border-radius:8px;cursor:pointer}.dlv-settings label.dlv-preset:has(input:checked){border-color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-1)}.dlv-settings label.dlv-preset input{width:auto;margin-top:3px}.dlv-preset span{display:grid;gap:3px}.dlv-vad-summary{font-weight:500}
.dlv-settings-actions{display:flex;flex-wrap:wrap;gap:8px}.dlv-settings-actions button{padding:8px 12px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-layer-1);color:inherit;cursor:pointer}.dlv-settings-actions button:disabled{opacity:.45;cursor:default}
@media(max-width:480px){.dlv-settings-heading{gap:6px}.dlv-heading-divider{min-width:4px}.dlv-settings-heading .dlv-star-badge{padding:3px 6px;font-size:10px}.dlv-preset-group{grid-template-columns:1fr}.dlv-pill{flex-wrap:wrap}.dlv-wave{flex-basis:90px}.dlv-status{flex-basis:100px}}
`;
export default styles;
